### ISSUE TITLE
Boolean parameter transfer problem

### ISSUE THREAD

**Issue by beilly** [tuenti/SmsRadar#10]
boolean notifyForDescendents = true; 
contentResolver.registerContentObserver(smsUri, notifyForDescendents, smsObserver); 
what is different to “contentResolver.registerContentObserver(smsUri, true, smsObserver); 
”？and you have used many in your code...

**Comment by pedrovgs** [comment]
Hi @shibenli there is no difference between: 

``` java
boolean notifyForDescendents = true; 
contentResolver.registerContentObserver(smsUri, notifyForDescendents, smsObserver); 
```

and

``` java
contentResolver.registerContentObserver(smsUri, true, smsObserver); 
```

We used to extract the true hardcoded values to local variables to improve the code readability. 

Is this the answer to your questions?

**Comment by beilly** [comment]
@pedrovgs , thank you very much.That can improve the "true" means function,and it's highly readable code
