### ISSUE TITLE
Cannot resolve symbol 'SmsRadarService'

### ISSUE THREAD

**Issue by giwrgos88** [tuenti/SmsRadar#3]
Hello, I have added the compile 'com.tuenti.smsradar:library:1.0.4' in the dependencies of my gradle and when I added the service tag inside my Android manifest I'm getting this warning "Cannot resolve symbol 'SmsRadarService'" How I can fix it? Thank you

**Comment by aakash94** [comment]
I am facing same problem, How did you resolve this ? @giwrgos88

**Comment by vladkalyuzhny** [comment]
```
     <service
            android:name="com.tuenti.smsradar.SmsRadarService"
            android:exported="false"
            android:label="@string/app_name"/>
```
